#!/usr/bin/env php
<?php

// Check if any arguments were passed (excluding the script name itself)
if (!isset($argv[1])) {
    echo 'no arguments provided.' . PHP_EOL;
    exit(1);
}

$command = $argv[1];
echo 'running ' . $command . PHP_EOL;

$daemonCommands = [ 'octane:start', 'serve', 'schedule:work', 'queue:work', 'octane:serve' ];
if (in_array($command, $daemonCommands)) while (true) sleep(5);