
# ------------------------------------------------------------------------------
# DEFAULT PRIORITY WORKER
# Focuses on default; will never process high or low jobs.
# ------------------------------------------------------------------------------
[program:laravel-worker-default]
command=php /var/www/html/artisan queue:work --queue=default --tries=3 --timeout=90
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0